/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Connection = Win32Connection | NetworkConnection | SerialConnection | DummyConnection;
export type PrintTask = TextTask | ImageTask | PdfTask | TableTask | FeedTask | CutTask | RawTask;
export type Request = PrintJobRequest | GetPrintersRequest | CheckStatusRequest | PrintCalibrationTextRequest;

export interface CheckStatusRequest {
  action: "check_status";
  connection: Connection;
}
export interface Win32Connection {
  type: "windows";
  printer_name: string;
}
export interface NetworkConnection {
  type: "network";
  host: string;
  port?: number;
  timeout?: number;
}
export interface SerialConnection {
  type: "serial";
  port: string;
  baudrate?: number;
  bytesize?: number;
  parity?: "N" | "E" | "O" | "M" | "S";
  stopbits?: number;
  timeout?: number;
  dsrdtr?: boolean;
}
export interface DummyConnection {
  type: "dummy";
}
export interface CutTask {
  type: "cut";
}
export interface FeedTask {
  type: "feed";
  lines?: number;
}
export interface GetPrintersRequest {
  action: "get_printers";
}
export interface ImageTask {
  align?: "left" | "center" | "right";
  type: "image";
  data: string;
}
export interface PdfTask {
  align?: "left" | "center" | "right";
  type: "pdf";
  data: string;
}
export interface PrintCalibrationTextRequest {
  action: "print_calibration_text";
  connection: Connection;
  start?: number;
  end?: number;
  step?: number;
}
export interface PrintJobRequest {
  action: "print";
  connection: Connection;
  profile: PrinterProfile;
  tasks: PrintTask[];
}
export interface PrinterProfile {
  left_margin_dots: number;
  print_width_dots: number;
  encoding?: string;
  codepage_id?: number | null;
}
export interface TextTask {
  align?: "left" | "center" | "right";
  type: "text";
  value: string;
}
export interface TableTask {
  align?: "left" | "center" | "right";
  type: "table";
  data: string[][];
  columns_ratio?: number[];
}
export interface RawTask {
  type: "raw";
  hex_data: string;
}
export interface SuccessResponse {
  status?: "success";
}
export interface PrinterInfo {
  name: string;
  port: string;
  driver: string;
}
export interface GetPrintersResponse {
  status?: "success";
  data: PrinterInfo[];
}
export interface PrinterStatusData {
  ready: boolean;
  online?: boolean;
  paper_out?: boolean;
  error?: string | null;
  details?: string | null;
  warning?: boolean;
}
export interface CheckStatusResponse {
  status?: "success";
  data: PrinterStatusData;
}
export interface ErrorResponse {
  status?: "error";
  error: string;
  message?: string | null;
  details?: unknown;
  traceback?: string | null;
}
